### ISSUE TITLE
Creation of weird scenario names in REMIND_climate_*.mif, when run after policyCosts

### ISSUE THREAD

**Issue by johanneskoch94** [remindmodel/remind#810] opened 2022-05-11 08:35 UTC
Addition by @orichters:
If a `REMIND_generic_*_adjustedPolicyCost.mif` is present in the output folder (from running [policyCosts](https://github.com/remindmodel/remind/blob/develop/scripts/output/comparison/policyCosts.R)), and then the `reporting` is repeated, the `REMIND_climate_*.mif` contains as scenario name `scenarioname_adjustedPolicyCost`, not `scenarioname`.

First, but probably wrong suspicion by @johanneskoch94:
The problem is probably here:

https://github.com/remindmodel/remind/blob/aff21de8cd564431caf4d84e4701fb88cb95b575/scripts/output/comparison/policyCosts.R#L314-L315

**Comment by orichters** [comment] 2022-05-11 08:43
I'm not sure, because `REMIND-Climate` seems not to be rewritten there. And the problem seems to arise only if `reporting.R` is run after the adjustedPolicyCosts mif was written.

**Comment by johanneskoch94** [comment] 2022-05-11 09:26
Ah ok, I misunderstood. The problem is not in the adjustedPolicyCosts reporting, but in the remind-Climate reporting okok.

**Comment by orichters** [comment] 2022-05-11 12:00
A way to reproduce it:
- Take a REMIND run that contains a `REMIND_generic_scenarioname.mif` file
- run output.R using `comparison` -> `policyCosts` and select this run twice (so `8,8` for example; or compare it to whatever base run you have)
- Look at `REMIND_climate_scenarioname.mif`. Everything is fine
- Using `output.R`, rerun `single` -> `reporting`
- Now, REMIND_climate_scenarioname.mif` contains as scenario name: `scenarioname_adjustedPolicyCosts`.
- If you copy `/p/tmp/oliverr/remind-smallfix/scripts/output/single/reporting.R` to your respective folder, it provides some logging and prints the full climate fill to the log before and after the sed / awk script

**Comment by orichters** [comment] 2022-05-11 12:52
The `-v` [here in `reporting.R`](https://github.com/remindmodel/remind/blob/develop/scripts/output/single/reporting.R#L49) seems to try pass the scenario name to the script for the variable `c_expname`, but it is then overwritten, as far as I understand it, by this line:
```
"ls ../REMIND_generic_*.mif" | getline c_expname
```

**Comment by giannou** [comment] 2022-05-11 13:00
tagging @0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment] 2022-05-12 09:55
Fixed in https://gitlab.pik-potsdam.de/REMIND/MAGICC/-/commit/7ac4851dde99f5a2b8c203142469b9941725b1d5

**Closed by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** 2022-05-12 09:55 UTC
Labels: bug

**Comment by orichters** [comment] 2022-05-12 09:57
Awesome, thanks @0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q for the quick fix!
