### ISSUE TITLE
Subsequent REMIND runs start even if basis-run fails or does not converge

### ISSUE THREAD

**Issue by giannou** [remindmodel/remind#173] opened 2020-05-13 12:08 UTC
We might want to change this

**Comment by orichters** [comment] 2022-03-22 13:02
The problem is even worse: Even if an `Execution Error` is raised, the run is counted as `completed` (including sending a mail stating that) as long as some `fulldata.gdx` was created in some iteration and therefore [modelstat reading works](https://github.com/remindmodel/remind/blob/develop/scripts/start/prepare_and_run.R#L893). An example run is `/p/tmp/oliverr/remind-tests/output/SSP2-Base_inv1_welf2_2022-03-18_11.59.07`. I would suggest to add an additional check like that:
```
if (! file.exists("full.log")  || ! grep("*** Status", readLines("full.log"), fixed = TRUE, value = TRUE) == "*** Status: Normal completion"))
   stop("GAMS run did not complete normally")
```
But I have no idea whether this would actually do what I intend or whether it should be implemented differently.

**Comment by LaviniaBaumstark** [comment] 2022-03-22 14:40
actually, we ant to start subsequent runs even if the reference scenarios did not converge. Sometimes a scenario just is not converging within 100 iterations but only fails in a few markets at the end of the century. Those results should not be used for papers or project submissions but can already be used to understand results and get more insights.

**Comment by giannou** [comment] 2022-03-23 07:51
The status of unconverged runs is still `Normal completion`, so the formulation with `Execution Errors` is better

**Comment by orichters** [comment] 2022-03-23 07:53
If unconverged runs return `Normal completion`, then I don't see a difference between the two implementations (as long as there is no third/fourth… status that I haven't seen yet).

**Comment by giannou** [comment] 2022-03-23 08:00
`Normal completion` means GAMS has done it's part and has finished without `Execution error(s)` or `Compilation error(s)`. Further statuses refer to what CONOPT and REMIND have achieved, these could be checked with `modelstats::getRunStatus`

**Comment by orichters** [comment] 2022-03-23 08:03
Ok, but then we should stick to the first formulation, where it checks whether the log states "*** Status: Normal completion". This covers both converged and unconverged runs, so this is fine, but Execution or Compilation errors both lead to a stop.

**Comment by orichters** [comment] 2022-04-19 08:49
I close this. REMIND now stops if run fails, but the start of subsequent runs if non-converged seems intended.

**Closed by orichters** 2022-04-19 08:49 UTC
Labels: bug, help wanted
