### ISSUE TITLE
reduce github repository size

### ISSUE THREAD

**Issue by giannou** [remindmodel/remind#302] opened 2021-01-19 11:48 UTC

**Comment by Renato-Rodrigues** [comment] 2021-03-05 19:19
Adding below some context and a suggestion for an approach to handle this issue.

**Description of the problem:**

The increased remind repository size was caused by updating binary files that are part of our version control list. They are represented by the gdx files used as input data in REMIND. 

Every time that any binary file is updated in a commit, git saves a copy of the old file to be able to restore the model to the previous state. As gdx files are already compressed formats and have in between 10-20 mb in file size in our case, every time they are updated the model size will increase by approximately the size of the replaced or deleted gdx file.   

You can check that only 18 gdx files, most of them that are not part of remind anymore, correspond to 90% of the recent git folder size increase by using the commands below:
```
git verify-pack -v .git/objects/pack/pack-a8707650a83bdb954302efdf1a999c297de61825.idx \
| sort -k 3 -n \
| tail -100

git rev-list --objects --all | grep  0f78fcba8ee03ea1e8d8407d4f3da5dd1a084e5f
```

**Why is this important:**

- Every time a change is made to the CES tree structure in REMIND, the input gdx file needs to be mandatorily updated for every region mapping used in the model.  
- Every time any meaningful changes are introduced at calibration level (ex: adjusting FE baseline trajectories, GDP levels,...) it is highly recommended to update the input.gdx file as this will not only speed up the first REMIND iteration (which takes much more time to solve than the other iterations), but also make sure that the model searches for a solution in the vicinity of the already tested calibration process.
- Alternative FE module realizations usually require specific input data gdxs.

So, it is right to assume that we will eventually need to update binary gdx files in the model and the repository will keep growing in size as time passes.

**Proposal for a solution:**

1. From now on, gdx commits should only be made if extremely necessary to avoid escalating the issue.
2. An alternative repository and version control system should be set in place to handle these binary files, and once this is done, all gdx files should be removed from the remind repository to this alternative repository. (ex. https://docs.gitlab.com/ee/topics/git/lfs/)
3. For the next full version of REMIND, gdx files should not be part of the repository and the git history should be edited to remove all gdx packed files (https://rtyley.github.io/bfg-repo-cleaner/ , https://github.com/newren/git-filter-repo). To keep backwards compatibility for older publications, the current repository should be copied with the git history intact to an alternative repository.

**Comment by orichters** [comment] 2022-10-12 16:45
Remind has surpassed 1GB. Maybe we should do said cleanup now?

**Comment by giannou** [comment] 2022-10-13 10:37
The repository size is not expected to grow further as gdx and other large files have been removed (thus addressing Renato's points above) and soon a check that doesn't allow adding files > 250kB will be added. Of course the > 1GB repository size problem still remains, but changing the git history in order to solve the problem is a very controversial issue. I am adding here Michaja's take on the issue for documentation purposes (bfg is a git size-reducing-and-history-rewriting tool https://rtyley.github.io/bfg-repo-cleaner/):

# git/bfg rant
* Limiting the size of new files added to REMIND is fine and sensible, no problem with that.
* Tempering with the commit history in order to reduce the repository size is unnecessary and foolish.
* If it is decided to do so, there are specific questions to be addressed and ready-made solutions to be provided beforehand to ensure REMIND work can continue.
   * I'm not positive the operation actually reduces the repository size.
   * The way bfg works is to re-create every commit, but with filters (in our case for large files) applied. But the old (large) commits are still present, until garbage collection is performed.
   * I'm not sure how/when garbage collection is performed on (free) Github accounts. Unless garbage collection is performed, all of the orphaned (large) commits are still part of the repository and will be downloaded on checkout, gaining us nothing.
   * This should be tested, including pushind upstream and checking out again, beforehand.
* The problem (of a large repository) is not insurmountable.
   * Checking out from Github on the cluster takes about one minute (time git clone https://github.com/remindmodel/remind.git).
   * Checking out from a local repository already in use takes less then a second (time git clone /p/tmp/pehl/Remind/).
   * It's easy to provide a script for local cloning that takes an exiting REMIND directory as a parameter, clones from there, and resets the origin remote to that of the existing repository. Then cloning locally is faster than cloning from upstream, no matter the size of the repository.
   * If people feel the pain from the large repository, they should have no problem picking up these easy techniques to speed up their work, especially if a script is provided.
   * This operation is going to f#$* mess up the entire git commit history. Which is a bad thing, because it is breaking the golden rule of git rebasing
> Do not rebase commits that exist outside your repository and that people may have based work on.

* We have external links to specific REMIND commits/tag from zenodo, that are part of our reproducible science and model transparency drive. We need to know what happens to links like https://github.com/remindmodel/remind/tree/v3.0.0 when the commits underlying these tags change. Possibly the tags need manual adjustment, possibly they are broken forever.
* Most important: We have external repositories that link specifically to the commit history.
Every develop branch on every REMIND repository (local and on Github) of every person working on REMIND does not link to whatever the develop branch on the REMIND Github repository happens to link to, but to the last know commit (identified by hash) that branch was pointing to. Changing the commit history (through bfg) will leave all branches in all repositories of all REMIND users dangling in mid-air.
* So in order for this operation to not crash REMIND work, there has to be a process to modify all repositories of all REMIND users to know about the new branches and use them. Otherwise there will be merge conflicts on each and every pull people are doing to get upstream changes.
* This also includes all feature branches people are working on that are not merged with the develop branch on the REMIND Github repository. The commit history of feature branches, which have a lot of person-hours of work in them, also include the entire history of the old (large) commits. Unless they are properly rebased, these old commits will be reintroduced into the commit history, increasing the the repository size back to its former glory, but duplicating each and every commit.
* This will show no conflicts prior to merging (since bfg does not change the tail commit) and the only indicator will be the the number of commits (≥ 3852) included in the merge request. Given the overall quality of reviews on our merge requests, somebody will approve and merge a request like that sooner or later.

**Comment by orichters** [comment] 2022-10-14 08:23
Thanks for the explanation, really seems no good idea. I guess we could even close here.

**Comment by Renato-Rodrigues** [comment] 2022-10-14 14:13
I would just want to add that another alternative also discussed at the time was that if we ever want to get ride of the big repository size we could: 
- create a new clean repository for a future REMIND release version and maintain the current history intact and saved in a locked alternative repository.

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment] 2022-10-17 10:15
(Restored the formatting that got lost during Anastasis' copying.)

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment] 2022-10-17 10:26
> * create a new clean repository for a future REMIND release version and maintain the current history intact and saved in a locked alternative repository.

That would mean to 
-  manipulate each and every directory somebody is using for REMIND work to point to the new repository (not terrible when a script is provided to users), 
- create new personal Github REMIND repositories for every user pointing to the new REMIND repository instead of the old, and changing all remotes on all working directories accordingly (so there needs some measure of configurability in the scripts)
- and to either
  - merge all feature branches people are working on back into `develop`
  - or throw away the commit history of the feature branches and treat them as single commits from the new `develop` branch

  both of which could result in merge conflict hell.

The advantage I see is that we wouldn't have to deal with garbage collection and that the "big" history can't inadvertently be merged back.

Not worth it in my view.

**Comment by mikapfl** [comment] 2022-11-17 15:47
Hi,

**abstract:**
I think we don't need to rewrite our git history, we just have to update documentation so that people use the right git flags when cloning. With the right git documentation, not all historical objects are fetched from github on clone. Either local objects are used (on the cluster) or only the interesting part of the historical objects are fetched initially (everywhere else).

**details:**
I looked into the whole issue a bit more. We are not the first people to have this problem, and there are already really good solutions which don't involve reqriting history. In particular, I have found two things, so I think we *don't* have to decrease the repo size:

1. What Michaja suggested regarding cloning from an already existing clone on the cluster exists even more advanced in git. It is spelled `git clone --reference /path/to/oldclone https://github.com/remindmodel/remind`. It works beautifully in my testing, even reducing storage demand because the new clone just contains pointers to the git objects in the reference repository. Since git objects are unique by their hash, this works as long as the reference is never deleted (and it remains super fast as long as the reference is pulled frequently). If we provide a central canonical reference source on the cluster, this should be really nice.
2. Regarding clones outside the cluster, `--filter` is our friend. Using it, the full git history is cloned, but not all historical git objects are fetched initially. Instead, only small historical objects are fetched and the big ones are fetched on demand. Given a good filter, this "on demand" will essentially be "never", e.g. setting the filter so that objects above 1 Megabyte in size are not fetched:
```bash
~/temp/filter> time git clone --filter=blob:limit=1m  github:remindmodel/remind
Cloning into 'remind'...
remote: Enumerating objects: 30182, done.
remote: Counting objects: 100% (1171/1171), done.
remote: Compressing objects: 100% (595/595), done.
remote: Total 30182 (delta 685), reused 973 (delta 570), pack-reused 29011
Receiving objects: 100% (30182/30182), 11.59 MiB | 6.01 MiB/s, done.
Resolving deltas: 100% (21737/21737), done.
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (1/1), 2.22 MiB | 3.06 MiB/s, done.
Updating files: 100% (1024/1024), done.

________________________________________________________
Executed in    7,22 secs    fish           external
   usr time    1,74 secs  809,00 micros    1,74 secs
   sys time    0,30 secs  336,00 micros    0,30 secs

~/temp/filter> du -sh remind/
39M	remind/
~/temp/filter> cd remind/
config  modules  standalone    DESCRIPTION    main.gms  pull_request_template.md  start_bundle_coupled.R
core    renv     tutorials     ignoreFiles.R  Makefile  README.md                 start_coupled.R
doc     scripts  CITATION.cff  LICENSE        output.R  start.R                   start_windows.cmd
~/temp/filter/remind (develop|✔)> 
```

If you specify the `--filter` limit too low, performance of commands that need the full history (like `git blame`) is pretty bad. But with a sufficiently large `--filter` limit, only the problematic big objects are not fetched, and `git blame` on normal files is fast, but e.g. `git checkout` of a really old commit which still contains the big files will be slow because the big git objects need to be fetched on demand. If you really need a full checkout of remind as it was 2 years ago, I think it is fine to wait a bit until everything is downloaded.

**Closed** 2023-02-16 17:52 UTC
Labels: minor
