### ISSUE TITLE
readCheckScenarioConfig() first asks whether to ignore settings, to then break on them

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [remindmodel/remind#1377] opened 2023-08-15 07:12 UTC
https://github.com/remindmodel/remind/blob/8ecf8fb6c1f281fca35a4280fce5a3518a5c3572/scripts/start/readCheckScenarioConfig.R#L115-L165

```
Automated checks did not find counterparts in main.gms and default.cfg for these columns in scenario_config_rev3p0p0_fdstk.csv:
  cm_bioenergy_tax, cm_bioenergymaxscen, cm_bioprod_histlim, cm_BioImportTax_EU, c_BaselineAgriEmiRed, cm_ariadne_VRECapFac_adj, cm_INNOPATHS_adj_coeff_multiplier, cm_INNOPATHS_adj_seed_multiplier, cm_regiCO2target, cm_OILRETIRE, cm_tradecost_bio
This check was added Jan. 2022. If you find false positives, add them to knownColumnNames in start/scripts/readCheckScenarioConfig.R.

Do you want to continue and simply ignore them? Y/n

Column name cm_bioenergy_tax in remind settings is outdated. Rename to cm_bioenergy_SustTax, see https://github.com/remindmodel/remind/pull/1003
Column name cm_bioenergymaxscen in remind settings is outdated. Use more flexible cm_maxProdBiolc switch instead, see https://github.com/remindmodel/remind/pull/1054
Column name cm_tradecost_bio in remind settings is outdated. Use more flexible cm_tradecostBio switch, see https://github.com/remindmodel/remind/pull/1054
Column name c_BaselineAgriEmiRed in remind settings is outdated. Use more flexible c_agricult_base_shift switch instead, see https://github.com/remindmodel/remind/issues/1157
Column name cm_bioprod_histlim in remind settings is outdated. Use more flexible cm_bioprod_regi_lim switch instead, see https://github.com/remindmodel/remind/issues/1157
Column name cm_BioImportTax_EU in remind settings is outdated. Use more flexible cm_import_tax switch instead, see https://github.com/remindmodel/remind/issues/1157
Column name cm_OILRETIRE in remind settings is outdated. Now always on by default, see https://github.com/remindmodel/remind/pull/1102
Error in readCheckScenarioConfig(config.file, ".") : 
  7 errors found, see explanation in warnings.
In addition: Warning message:
In readCheckScenarioConfig(config.file, ".") :
  Outdated column names found that must not be used.
Execution halted
```

Break on "forbidden" columns before asking to ignore them.

**Comment by orichters** [comment] 2023-08-15 11:43
Fixed in https://github.com/remindmodel/remind/pull/1378

New behavior:

If forbidden names exist, it fails but doesn't ask to ignore them. The forbidden column names are not included in the unknowns anymore:
```
Column name cm_bioenergy_tax in remind settings is outdated. Rename to cm_bioenergy_SustTax, see https://github.com/remindmodel/remind/pull/1003
Column name cm_bioenergymaxscen in remind settings is outdated. Use more flexible cm_maxProdBiolc switch instead, see https://github.com/remindmodel/remind/pull/1054
Column name cm_tradecost_bio in remind settings is outdated. Use more flexible cm_tradecostBio switch, see https://github.com/remindmodel/remind/pull/1054
Column name c_BaselineAgriEmiRed in remind settings is outdated. Use more flexible c_agricult_base_shift switch instead, see https://github.com/remindmodel/remind/issues/1157
Column name cm_bioprod_histlim in remind settings is outdated. Use more flexible cm_bioprod_regi_lim switch instead, see https://github.com/remindmodel/remind/issues/1157
Column name cm_BioImportTax_EU in remind settings is outdated. Use more flexible cm_import_tax switch instead, see https://github.com/remindmodel/remind/issues/1157
Column name cm_OILRETIRE in remind settings is outdated. Now always on by default, see https://github.com/remindmodel/remind/pull/1102

Automated checks did not find counterparts in main.gms and default.cfg for these columns in scenario_config_rev3p0p0_fdstk.csv:
  cm_ariadne_VRECapFac_adj, cm_INNOPATHS_adj_coeff_multiplier, cm_INNOPATHS_adj_seed_multiplier, cm_regiCO2target
This check was added Jan. 2022. If you find false positives, add them to knownColumnNames in start/scripts/readCheckScenarioConfig.R.

Error in `readCheckScenarioConfig()`:
! 7 errors found, see explanation in warnings.
```

If you remove the forbidden names, it asks as intended:
```
Automated checks did not find counterparts in main.gms and default.cfg for these columns in scenario_config_rev3p0p0_fdstk_nofails.csv:
  cm_ariadne_VRECapFac_adj, cm_INNOPATHS_adj_coeff_multiplier, cm_INNOPATHS_adj_seed_multiplier, cm_regiCO2target
This check was added Jan. 2022. If you find false positives, add them to knownColumnNames in start/scripts/readCheckScenarioConfig.R.

Do you want to continue and simply ignore them? Y/n
Y
```

**Closed** 2023-08-15 13:32 UTC
Labels: bug
